# Generated by Django 5.0.3 on 2024-04-28 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="users.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="show",
            name="ticket",
            field=models.ManyToManyField(default="true", to="users.ticket"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="card_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="cvv",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="BookingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_number", models.IntegerField(unique=True)),
                ("ticket_number", models.IntegerField()),
                (
                    "customer",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_histories",
                        to="users.customer",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.show"
                    ),
                ),
            ],
        ),
    ]
