# Generated by Django 5.0.3 on 2024-04-28 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_bookings_customer_show_ticket_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookings",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="creditcard",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="bookinghistory",
            name="customer",
        ),
        migrations.AddField(
            model_name="bookinghistory",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_histories",
                to="users.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="bookings",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="users.userprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="creditcard",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.userprofile",
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
