# Generated by Django 4.2.10 on 2024-03-26 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_subscribe_to_promotions'),
        ('users', '0003_userprofile_register_for_promotions'),
    ]

    operations = [
    ]
