# Generated by Django 5.0.3 on 2024-04-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_bookings_customer_remove_creditcard_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="showtime",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.showtimes",
            ),
            preserve_default=False,
        ),
    ]
