# Generated by Django 5.0.3 on 2024-03-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_20240326_0045"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="register_for_promotions",
        ),
    ]
