# Generated by Django 4.2.10 on 2024-03-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20240326_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='register_for_promotions',
        ),
    ]
