# Generated by Django 5.0.3 on 2024-04-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userprofile_password_creditcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="card_number",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="cvv",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
