# Generated by Django 5.0.3 on 2024-04-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_creditcard_card_number_alter_creditcard_cvv"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
