# Generated by Django 4.2.10 on 2024-04-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_customer_subscribe_to_promotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='subscribe_to_promotions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
