# Generated by Django 5.0.3 on 2024-04-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_movie_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cast",
            field=models.TextField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.TextField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="movie",
            name="producer",
            field=models.TextField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="movie",
            name="reviews",
            field=models.TextField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[("nowPlaying", "Now Playing"), ("comingSoon", "Coming Soon")],
                default="nowPlaying",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(default="None", max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("g", "G"),
                    ("pg", "PG"),
                    ("pg13", "PG13"),
                    ("r", "R"),
                ],
                default="none",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
