# Generated by Django 5.0.3 on 2024-04-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_movie_cast_movie_director_movie_producer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="reviews",
            new_name="review",
        ),
    ]
