# Generated by Django 5.0.3 on 2024-04-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/assets/img/gallery"
            ),
        ),
    ]
