# Generated by Django 5.0.3 on 2024-04-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(default="None", max_length=200),
        ),
        migrations.AlterField(
            model_name="movie",
            name="review",
            field=models.TextField(default="None", max_length=200),
        ),
    ]
