# Generated by Django 4.2.10 on 2024-04-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customer_subscribe_to_promotions_delete_user'),
        ('users', '0014_alter_movie_description_alter_movie_review'),
    ]

    operations = [
    ]
