# Generated by Django 4.2.10 on 2024-04-19 00:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20240419_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='date',
        ),
        migrations.RemoveField(
            model_name='show',
            name='duration',
        ),
        migrations.AddField(
            model_name='show',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.movie'),
        ),
        migrations.AddField(
            model_name='show',
            name='showroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.showroom'),
        ),
        migrations.AddField(
            model_name='show',
            name='showtime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.showtimes'),
        ),
        migrations.AddField(
            model_name='showtimes',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='showtimes',
            name='showroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.showroom'),
        ),
        migrations.AddField(
            model_name='showtimes',
            name='time_slot',
            field=models.CharField(choices=[('Morning', '09:00-12:00'), ('Afternoon', '12:00-15:00'), ('Evening', '15:00-18:00'), ('Night', '18:00-21:00')], default='Morning', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='showtimes',
            unique_together={('date', 'time_slot', 'showroom')},
        ),
        migrations.RemoveField(
            model_name='showtimes',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='showtimes',
            name='start_time',
        ),
    ]
